name = "hochmut-cloud"
compatibility_date = "2026-04-13"
pages_build_output_dir = "."

[vars]
GUILD_NAME = "Hochmut"
DISCORD_INVITE = ""

[[d1_databases]]
binding = "DB"
database_name = "hochmut-gears"
database_id = "91c43dbb-d656-45cb-8fc7-7b0726411699"
preview_database_id = "91c43dbb-d656-45cb-8fc7-7b0726411699"
migrations_dir = "db"
